# Campaign Channel Configuration
# Defines the default channels to create for each campaign
#
# Channel Types:
#   text: Text channel (0)
#   voice: Voice channel (2)
#   forum: Forum channel (15)
#
# GM-Only Channels:
#   Set gm_only: true to restrict access to guild owner, admins, and GM role

channels:
  # Text Channels
  - name: general-discussion
    type: text
    gm_only: false
    description: General campaign discussion

  - name: session-recaps  
    type: text
    gm_only: false
    description: Session summaries and notes

  - name: gm-notes
    type: text
    gm_only: true
    description: Private GM planning and notes

  # Voice Channels
  - name: voice-chat
    type: voice
    gm_only: false
    description: Voice channel for sessions

  # Forum Channels
  - name: character-and-npcs
    type: forum
    gm_only: false
    description: Character and NPC sheets and builds

  - name: campaign-lore
    type: text
    gm_only: false
    description: Campaign lore and world information

  - name: session-zero
    type: text
    gm_only: true
    description: Session Zero and GM planning

  - name: maps-and-visuals
    type: text
    gm_only: true
    description: Maps and campaign visuals

  - name: dice-rolls
    type: text
    gm_only: true
    description: Dice rolls amnd results

  - name: safety-checks
    type: text
    gm_only: true
    description: Safety checks and information
